## AWS CONFIG ##
aws.dynamodb.endpoint=http://localhost:4566
aws.dynamodb.accessKey=test
aws.dynamodb.secretKey=test
aws.region=sa-east-1
aws.profile=localstack

## SERVER PORT ##
server.port=9595

## SPRING CONFIG ##
spring.profiles.active=localstack

## Habilita cores ANSI no console de forma forçada
spring.output.ansi.enabled=ALWAYS

## Padrão de exibição do log no console (Data simples, Nível colorido, Thread, Pacote resumido e Mensagem)
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

## Reduz o nível de log de bibliotecas internas ruidosas (Tomcat, Spring Framework)
logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.apache.catalina=WARN
logging.level.software.amazon.awssdk=WARN

## Define o nível de log da sua aplicação como DEBUG (para ver chamadas da sua regra de negócio)
logging.level.br.com.dynamodb=DEBUG

## Formato de log estruturado nativo do Spring Boot 3.4+
logging.structured.format.console=ecs